### ISSUE TITLE
Enhancement: note editing from the application home

### ISSUE THREAD

**Issue by petrux** [net7/pundit2#2]
As far as I could get, it is not possible to edit notes from the application page, If I am right and such behavior is not supported, I think it should be. Otherwise, maybe the option should be made just easier to get. :-)

**Comment by gandreini** [comment]
You are right, at the moment is not possible to edit annotations from Pundit app. It's only possible to delete them. This is a good suggestion for a future improvement. Thank you :)

**Comment by petrux** [comment]
You are welcome! Can I close the issue?

**Comment by gandreini** [comment]
Yes thanks
