### ISSUE TITLE
Selection non editable

### ISSUE THREAD

**Issue by petrux** [net7/pundit2#3]
Scenario: I selected a sentence from a webpage and wrote my annotation. After that, I noticed that I left out the first letter of the sentence. I went for edit the annotation and change the selection, but it seems that there is no way.

**Comment by gandreini** [comment]
This is not possible at the moment for highlights and comments. We will consider this as a future enhancement.

**Comment by petrux** [comment]
You are welcome. All the obessive-compulsive like me would found this enhancement really useful. :-)
