### ISSUE TITLE
Default context menu is disabled

### ISSUE THREAD

**Issue by petrux** [net7/pundit2#4]
If I select some piece of text with Pundit active, the context menu is disabled.
This is a major bug, as I might need just to copy some text.

P.S. using Chrome on Ubuntu 14.04.

**Comment by gandreini** [comment]
Hi @petrux at the moment this is necessary to highlight the selected text. Anyway we can consider some different solutions. I'll open a ticket in our ticketing system.
As a momentary solution consider you can COPY the text if you select it, before releasing the mouse button (while still clicking).

**Comment by petrux** [comment]
Hello and thanks for the quick reply. My (humble) point of view is to integrate the Pundit functionalities in the context menu. :-) Thanks!

**Comment by gandreini** [comment]
That's also an interesting suggestion. We prefer not to have Pundit functionalities in the contextual menu since they would be a bit hidden to new users. But there are some situations where this could be useful.

**Comment by petrux** [comment]
Ok. Have you scheduled the enhancement? -- so I can close the issue.

**Comment by gandreini** [comment]
Hi Giulio, we created a ticket in our private ticketing system. Thank you
